# Generated by Django 4.0 on 2023-11-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0002_infomation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomation',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
