# Generated by Django 4.0 on 2023-11-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0003_infomation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomation',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
