# Generated by Django 4.0 on 2023-11-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0005_alter_infomation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomation',
            name='image',
        ),
    ]
