# Generated by Django 4.0 on 2023-11-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0006_remove_infomation_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomation',
            old_name='title',
            new_name='infomation_title',
        ),
    ]
