# Generated by Django 4.0 on 2023-11-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0007_rename_title_infomation_infomation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomation',
            old_name='infomation_title',
            new_name='title',
        ),
    ]
