# Generated by Django 4.0 on 2023-12-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0008_rename_infomation_title_infomation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomation',
            name='category',
            field=models.CharField(choices=[('update', 'アップデート'), ('infomation', 'お知らせ'), ('competition', '競技情報'), ('maintenance', 'メンテナンス')], default='infomation', max_length=30, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='infomation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='infomation',
            name='message',
            field=models.TextField(verbose_name='お知らせ内容'),
        ),
        migrations.AlterField(
            model_name='infomation',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='infomation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
