# Generated by Django 4.0 on 2023-12-26 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_total_score'),
        ('infomation', '0009_alter_infomation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomation',
            name='autohr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', to_field='username', verbose_name='投稿者'),
        ),
    ]
