# Generated by Django 4.0 on 2023-12-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='総合得点'),
        ),
    ]
