# Generated by Django 4.0 on 2023-11-28 02:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(regex='^#[0-9]{2}')])),
                ('disription', models.TextField(default='')),
                ('visible', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('WebExploitation', 'WebExploitation'), ('Cryptography', 'Cryptography'), ('Reversing', 'Reversing'), ('Pwnable', 'Pwnable'), ('Forensics', 'Forensics'), ('Network', 'Network'), ('GenerallSkill', 'GenerallSkill'), ('Misc', 'Misc')], default='Misc', max_length=30)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise',
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-Z]*$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-Z]*$')])),
                ('title', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(regex='^[0-9]{2}[.]{1}')])),
                ('category', models.CharField(choices=[('WebExploitation', 'WebExploitation'), ('Cryptography', 'Cryptography'), ('Reversing', 'Reversing'), ('Pwnable', 'Pwnable'), ('Forensics', 'Forensics'), ('Network', 'Network'), ('GenerallSkill', 'GenerallSkill'), ('Misc', 'Misc')], default='Misc', max_length=30)),
                ('problem', models.TextField(default='')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)])),
                ('flag', models.CharField(default='', max_length=100)),
                ('visible', models.BooleanField(default=False)),
                ('hint_one', models.CharField(blank=True, default='', max_length=100)),
                ('hint_two', models.CharField(blank=True, default='', max_length=100)),
                ('hint_three', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exerciseName', models.ForeignKey(default='実戦問題', on_delete=django.db.models.deletion.SET_DEFAULT, to='challenges.exercise')),
            ],
            options={
                'verbose_name': 'Challenges',
            },
        ),
    ]
