# Generated by Django 4.0 on 2023-12-26 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_exercise_thumbnail_exercise_explanation_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('WebExploitation', 'WebExploitation'), ('Cryptography', 'Cryptography'), ('Reversing', 'Reversing'), ('Pwnable', 'Pwnable'), ('Forensics', 'Forensics'), ('Network', 'Network'), ('GenerallSkill', 'GenerallSkill'), ('Misc', 'Misc')], default='Misc', max_length=30, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='disription',
            field=models.TextField(default='', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(regex='^#[0-9]{2}')], verbose_name='演習名'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='explanation_url',
            field=models.URLField(default='', verbose_name='解説URL'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reference_url',
            field=models.URLField(default='', verbose_name='教科書URL'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='ユーザへの公開'),
        ),
    ]
